name: CD - Main Branch Deployment to Docker Hub

on:
  push:
    branches: [main]

jobs:
  # 1. Run NPM Build and Test (Final confirmation before deployment)
  app_ci_check:
    name: Application Build & Test
    # Using the path specified in your query
    uses: ./.github/workflows/build-test-ci.yml

  # 2. Job to set dynamic variables (must run before deployment)
  set_variables:
    name: Set Deployment Variables
    runs-on: ubuntu-latest
    needs: app_ci_check
    outputs:
      # Expose the calculated IMAGE_TAG as a job output
      image_tag: ${{ steps.set_tag.outputs.IMAGE_TAG }}
    steps:
      - name: Set Image Variable
        id: set_tag
        # Since GitHub Actions expressions don't support string slicing functions (like substring or slice),
        # we must use string indexing for the 7-character SHA to pass the output correctly.
        run: echo "IMAGE_TAG=image-test:$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_OUTPUT

  # 3. Push Image to Docker Hub (requires app tests to pass)
  deploy_image:
    name: Push to Docker Hub
    needs: [app_ci_check, set_variables]
    # Using the path specified in your query
    uses: ./.github/workflows/docker-push-ci.yml
    with:
      # Defining the constants directly here resolves the 'env' lookup error
      image_name: n8nny/lseg-immersion-day-2025-front-end-devops
      tag: ${{ needs.set_variables.outputs.image_tag }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
